#! /usr/bin/env python

"""
Script to find JPG files that were exported from RAW into the same directory
"""

import os

if __name__ == "__main__":

    for root, dirs, files in os.walk('.'):
        jpgs = filter(lambda x:'.jpg' in x, files)
        for jpg in jpgs:
            base, _dummy = os.path.splitext(jpg)
            xmp = base + '.xmp'
            cr2 = base + '.cr2'
            crw = base + '.crw'
            if xmp in files and (cr2 in files or crw in files):
                print "Should delete", os.path.join(root, jpg)
