#! /bin/sh

# Remove ID place holders from keywords

grep ID- "Lightroom Keywords - Possible.txt" > "ID hierarchy.txt"

grep -v ID- "Lightroom Keywords.txt" > tmp.txt
mv tmp.txt "Lightroom Keywords.txt"
grep -v ID- "Lightroom Keywords - Possible.txt" > tmp.txt
mv tmp.txt "Lightroom Keywords - Possible.txt"
