#! /usr/bin/env python
# -*- coding: utf-8 -*-

import subprocess
import os
import sys
import optparse
import re
import time

def exivGetTitle(fileName):
    keywordList = []
    cmd =  'exiv2 -Pt -g Iptc.Application2.ObjectName "%s"' % (fileName)
    try:
        status, output = subprocess.getstatusoutput(cmd)
        if output:
            return output
    except:
        pass

    return None

# This is the same function as SetTitlesFromKeywords

def exivSetCaption(fileName, caption=None, override=False):
    """
    Set (by setting one) the following EXIF tags:

        Exif.Image.ImageDescription                  Ascii       8  caption
        Iptc.Application2.Caption                    String      7  caption
        Xmp.dc.description                           LangAlt     1  lang="x-default" caption
    """

    if not caption:
        return False

    try:
        cmd =  'exiv2 -Pt -g Iptc.Application2.Caption "%s"' % (fileName)
        status, output = subprocess.getstatusoutput(cmd)
        if output:
            return False
    except:
        return False

    try:
        cmd =  'exiv2 -M"set Iptc.Application2.Caption String %s" "%s"' % (caption, fileName)
        status, output = subprocess.getstatusoutput(cmd)
    except:
        print("Could not set caption for ", fileName)
        return False

    return True

if __name__ == "__main__":

    """
    Set titles and captions from keywords
    """

    # parser = optparse.OptionParser(usage="usage: %prog [options]")
    #
    # parser.add_option(
    #         "-n",
    #         action="store_true", dest="test",
    #         help="Don't change any files, print what would happen")
    #
    # args = sys.argv
    # (options, args) = parser.parse_args(args)

    fileNames = []
    metaFile = re.compile(r'[ \w\-]+\.(xmp)')

    # Collect list of XMP files
    for fileName in os.listdir('.'):
        if metaFile.match(fileName):
            fileNames.append(fileName)

    for fileName in fileNames:
        # Find photos that satisfy the rules (one more more Animals, nothing needing further ID)
        title = exivGetTitle(fileName)
        setCaption = exivSetCaption(fileName, caption=title, override=False)
        if setCaption:
           print(fileName, 'set to "%s"' % title)
