#! /usr/bin/env python

import os
import re
import subprocess
import string

flacPath = '/Volumes/Archive/CDs-flac/'
alacPath = '/Users/ewv/data/CDs-alac/'
xld = '/Users/ewv/bin/xld'

# TODO: Bidirectional
# TODO: Detect timestamps, touch original file as well to match timestamps
# TODO: Command line params for matching
# TODO: Break out as functions as needed


if __name__ == "__main__":

	for root, dirs, files in os.walk(alacPath):
 		if string.find(root, 'Various Artists') != -1:
 			pass
# 			continue

		for file in files:
			if file.endswith('.m4a'):
				alacFile = os.path.join(root, file)

				flacBase = re.sub('^%s' % alacPath, flacPath, root)
				flacShort = re.sub('%s$' % 'm4a', 'flac', file)
 				flacFile = os.path.join(flacBase, flacShort)
 				if not os.path.exists(flacBase):
 					os.makedirs(flacBase)
 				if not os.path.exists(flacFile):
 					print "Converting", alacFile, 'to flac'
 					subprocess.call([xld, '-f', 'flac', '-o', flacFile, alacFile])
