#! /usr/bin/env python

import os
import re
import subprocess
import string

flacPath = '/Volumes/data-vondo/CDs/flac/'
alacPath = '/Users/ewv/data/CDs/alac/'
xld = '/Users/ewv/bin/xld'	


if __name__ == "__main__":
	
	for root, dirs, files in os.walk(flacPath):
#		print root, dirs, files
#		print string.find(root, 'U2')
 		if string.find(root, 'Lovett') == -1:
 			continue	

		for file in files:
			if file.endswith('.flac'):
				flacFile = os.path.join(root, file)
				
				alacBase = re.sub('^%s' % flacPath, alacPath, root)		
				

				alacShort = 	re.sub('%s$' % 'flac', 'm4a', file)	
 				alacFile = os.path.join(alacBase, alacShort)
 				if not os.path.exists(alacBase):
 					os.makedirs(alacBase)
 				print "Converting", flacFile
 				if not os.path.exists(alacFile):
 					pass
 					subprocess.call([xld, '-f', 'alac', '-o', alacFile, flacFile])
# 					print flacFile, 'to', alacFile
 					
