#! /usr/bin/env python

import os
import re
import subprocess
import string

flacPath = '/Volumes/data-vondo/CDs/flac/'
alacPath = '/Users/ewv/data/CDs/alac/'
xld = '/Users/ewv/bin/xld'	

# TODO: Bidirectional
# TODO: Detect timestamps, touch original file as well to match timestamps
# TODO: Command line params for matching
# TODO: Break out as functions as needed


if __name__ == "__main__":
	
	for root, dirs, files in os.walk(flacPath):
 		if string.find(root, 'Various Artists') != -1:
 			pass
# 			continue	

		for file in files:
			if file.endswith('.flac'):
				flacFile = os.path.join(root, file)
				
				alacBase = re.sub('^%s' % flacPath, alacPath, root)		
				alacShort = re.sub('%s$' % 'flac', 'm4a', file)	
 				alacFile = os.path.join(alacBase, alacShort)
 				
 				if not os.path.exists(alacBase):
 					os.makedirs(alacBase)
 				if not os.path.exists(alacFile):
 					print "Converting", flacFile, 'to m4a'
 					subprocess.call([xld, '-f', 'alac', '-o', alacFile, flacFile])
 					
