#! /usr/bin/env python

import os
import re
import shutil
#import subprocess
#import string

flacPath = '/Volumes/data-vondo/CDs/flac/'
alacPath = '/Users/ewv/data/CDs-alac/'
aacPath = '/Volumes/Archive/CDs-aac/'

jpgPath = '/Volumes/Archive/Misc/graphics/CD Covers/'

# TODO: Bidirectional
# TODO: Detect timestamps, touch original file as well to match timestamps
# TODO: Command line params for matching
# TODO: Break out as functions as needed

def CopyToMusic(artist, album, root):
    """
    Copy from jpgPath to album folder
    """

    jpgFile = os.path.join(jpgPath, '%s-%s.jpg' % (artist, album))
    folderJpg = folderJPG = os.path.join(root, artist, album, 'folder.jpg')

    if os.path.exists(jpgFile) and not os.path.exists(folderJpg):
        print "Found a new JPG", jpgFile, 'to copy to', folderJpg
        shutil.copy2(jpgFile, folderJPG)

    return


if __name__ == "__main__":

    for root, dirs, files in os.walk(aacPath):
        if root != aacPath and dirs:
        	dummy, artist = os.path.split(root)
        	for album in dirs:
        		CopyToMusic(artist, album, aacPath)

    exit


    for root, dirs, files in os.walk(flacPath):
        for file in files:
            if file.endswith('folder.jpg'):
                folderJPG = os.path.join(root, file)

                dummy, album = os.path.split(root)
                dummy, artist = os.path.split(dummy)

                jpgFile = os.path.join(jpgPath, '%s-%s.jpg' % (artist, album))
                if not os.path.exists(jpgFile):
                    print "Found a new folder.jpg", folderJPG, 'to copy to', jpgFile
                    shutil.copy2(folderJPG, jpgFile)

    for root, dirs, files in os.walk(alacPath):
        folderJPG = os.path.join(root, 'folder.jpg')
        if not os.path.exists(folderJPG):
            try:
                dummy, album = os.path.split(root)
                dummy, artist = os.path.split(dummy)
                jpgFile = os.path.join(jpgPath, '%s-%s.jpg' % (artist, album))
                if os.path.exists(jpgFile):
                    print "Found a new JPG", jpgFile, 'to copy to', root
                    shutil.copy2(jpgFile, folderJPG)
            except:
                print "Problem parsing", root


